name: handle-mcpc-generator
on:
  workflow_dispatch:
    inputs:
      versions:
        description: 'JSON stringified list of known versions in generator (last is expected to be latest)'
        required: true
        default: '["1.21.6"]'
      mergedArtifactURL:
        description: 'Merged artifact download URL'
        required: true
      prNumber:
        description: 'Relevant minecraft-data-generator PR #'
        required: false

jobs:
  update-mcdata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Use Node.js 22.x
        uses: actions/setup-node@v1
        with:
          node-version: 22.x
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3
      - run: cd .github/helper-bot && npm install
      - run: cd tools/js && npm install
      - run: cd .github/helper-bot && node handleMcpcGeneratedArtifacts.js
        env:
          TRIGGER_MC_VERSIONS: ${{ github.event.inputs.versions }}
          TRIGGER_PR_NO: ${{ github.event.inputs.prNumber }}
          TRIGGER_ARTIFACT_URL: ${{ github.event.inputs.mergedArtifactURL }}
          GITHUB_TOKEN: ${{ secrets.PAT_PASSWORD }}
